language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy

before_install: if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install simplejson; fi

install: if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install -r requirements.py3.txt --use-mirrors; fi

script: python setup.py test

branches:
  except:
    - website

notifications:
  # Disable travis notifications until they figured out how to hide
  # their own builder failure from us.  Travis currently fails way
  # too many times by itself.
  email: false

  irc:
    channels:
      - "irc.freenode.org#pocoo"
    use_notice: true
    skip_join: true
