language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=lowest RUN_FLASK_MEMORY_TESTS=1
  - REQUIREMENTS=release
  - REQUIREMENTS=release RUN_FLASK_MEMORY_TESTS=1
  - REQUIREMENTS=devel
  - REQUIREMENTS=devel RUN_FLASK_MEMORY_TESTS=1

matrix:
  exclude:
    # Python 3 support currently does not work with lowest requirements
    - python: "3.3"
      env: REQUIREMENTS=lowest

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --editable .

script: make test

branches:
  except:
    - website

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
